### ISSUE TITLE
Xcode 11 GM. Could not find a class or protocol .... 

### ISSUE THREAD

**Issue by dandreikiv** [seanhenry/SwiftMockGeneratorForXcode#28]
Hi. I have switched to Xcode 11 GM and Mock Generator started to give me an error with message `Could not find a class or protocol ...`. In Xcode 10.3 everything worked fine.

**Comment by seanhenry** [comment]
Hi,

Thanks for raising this issue. 

The issue is fixed in the [latest release](https://github.com/seanhenry/SwiftMockGeneratorForXcode/releases/tag/v1-beta.21) but make sure you read the release notes to migrate successfully.

This issue was caused by SourceKit in Xcode 11. It now requires an `-sdk` parameter pointing to a platform SDK. Unfortunately there's no easy way to automatically get the SDK so there is a new text field that must be filled in in the companion app. See [Setting the SDK path](https://github.com/seanhenry/SwiftMockGeneratorForXcode/tree/v1-beta.21#setting-the-sdk-path) for more information.

**Comment by seanhenry** [comment]
I've improved the Xcode 11 support now - no need to add an SDK path and fixed some performance issues. You can download that release [here](https://github.com/seanhenry/SwiftMockGeneratorForXcode/releases)
