### ISSUE TITLE
Closure parameter is not saved to a variable

### ISSUE THREAD

**Issue by LeonidKokhnovich** [seanhenry/SwiftMockGeneratorForXcode#3]
I have a protocol with this function declaration:
```
protocol MyProtocol {
    func add(observer: @escaping (SomeCustomType?) -> Void) -> Bool
}
```

The generated code looks like this:
```
    var invokedAdd = false
    var invokedAddCount = 0
    var stubbedAddObserverResult: (SomeCustomType?, Void)?
    var stubbedAddResult: Bool!
    func add(observer: @escaping (SomeCustomType?) -> Void) -> Bool {
        invokedAdd = true
        invokedAddCount += 1
        if let result = stubbedAddObserverResult {
            observer(result.0)
        }
        return stubbedAddResult
    }
```

So there is no way to get observer parameter in the test suite after this method has been called.

**Comment by seanhenry** [comment]
That's right. The way this mock works is to either:
- ignore the closure when the data was not stubbed, or
- call the closure with the stubbed data

By default the closure will not be called. But you can choose what data to call the closure with by:
```
mock.stubbedAddObserverResult = (SomeCustomType(), ())
```
or, if you want to call the closure with `nil`:
```
mock.stubbedAddObserverResult = (nil, ())
```
The reason the closures aren't captured by the mock is because not all closures are `@escaping` and non-escaping closures would cause a compiler error when captured.

 For example, this mock would not compile because the closure is not marked as escaping:
```
var invokedAddParameters: (() -> (), Void)?
func method(closure: () -> ()) {
  invokedAddParameters = (closure, ()) // This line causes a compiler error
}
```

**Comment by LeonidKokhnovich** [comment]
Thank you for the response! Is it possible to capture closures that are marked with "@escaping"?

**Comment by seanhenry** [comment]
It is possible, but the mock isn't clever enough to figure that out yet. I would recommend subclassing mocks when you need some extra behaviour. For example your mock could be subclassed like this to get your custom behaviour:
```
class CustomMock: YourMock {
  
  var capturedObserver: ((SomeCustomerType?) -> Void)?

  override func add(observer: @escaping (SomeCustomType?) -> Void) -> Bool {
    super.add(observer: observer) // the mock will still behave as normal
    capturedObserver = observer
  }
}
```

**Comment by LeonidKokhnovich** [comment]
That's one of the possible solutions. I hope this feature can be added in the future! 
I would suggest keeping this issue opened till the feature is added or feel free to close it if you disagree.
Thank you for support!

**Comment by seanhenry** [comment]
I'm not sure I will add it as a feature because it would mean escaping and non-escaping closures would be handled differently and there would be 2 ways to call escaping closures (either by capturing one as a parameter, or by stubbing the closure data).

I can see the benefit of capturing a closure though. Would you be interested in [this feature](https://github.com/seanhenry/MockGenerator/issues/14) which would allow you to create your own mock template?

**Comment by LeonidKokhnovich** [comment]
Thank you for the response!
I checked that page, but it's still not clear to me what is the idea behind the mock template.
I don't see any mocking sample with a protocol there. Could you please provide more details how it can help to capture escaping closures?

**Comment by seanhenry** [comment]
It’s a feature that hasn’t been developed yet but the idea behind it is that it gives you the freedom to create your own style of mock. So in this case, you would be able to change the template to include closures in the parameter list. 

After speaking to some developers they like the plugin but would prefer the mocks to be generated in their own style. Is it something you’d be interested in seeing in the future?

**Comment by LeonidKokhnovich** [comment]
If that feature can introduce an option to customize mocking behavior, that would be great. But I also think there should be a default template so devs can use it without getting too deep into the mock generator capabilities.

**Comment by seanhenry** [comment]
That's right. There would be a default template and you would be able to have one or more custom mock templates alongside.

**Comment by seanhenry** [comment]
I'll close this for now but will aim to support custom templates in the near future.
