### ISSUE TITLE
Mock generator fails to create mock code for a swift protocol

### ISSUE THREAD

**Issue by LeonidKokhnovich** [seanhenry/SwiftMockGeneratorForXcode#5]
While I was trying to generate a mock for a swift protocol, I saw an issue that it was failing multiple times in a row. Restarting Xcode / swift mock generator util sometimes helps. I can't provide a test project to check it out because have no idea how to reproduce it, but I have some ideas why it might be the issue:

1. Mock generator util fails to find the protocol after a certain timeout. It that's the case, would it be possible to customize the timeout time?
2. The mock generator has a limitation on folder recursive search. Example:
if limitation = 2, then folder1 -> folder1_subfolder_1 -> folder1_subfolder_1_subfolder_1 would fail.

Please, let me know your thoughts...

**Comment by seanhenry** [comment]
Hi, thanks for raising this issue. 

I don’t think the problem is the timeout or the recursive searching. I’ve tested with a reasonably large project and it seems to generate a mock in a few seconds (please let me know if that isn’t the case). 

Next time it happens could you send me the exact message and the approximate time it takes? 

The problem sounds like it is with SourceKit. It won’t be able to generate anything if Xcode is indexing. Next time Xcode is indexing, try and generate a mock and see if you get the exact same problem. If you do, then this could be it.

**Comment by LeonidKokhnovich** [comment]
@seanhenry The idea regarding SourceKit is quite possible.

"Next time it happens could you send me the exact message and the approximate time it takes?"
- Message - "Reachable element could not be resolved"
- Approximate time - ~19 seconds

**Comment by LeonidKokhnovich** [comment]
It the problem is with SourceKit indexing, can we give a warning message that indexing is in progress and you should try again later instead of waiting for ~19 seconds and giving an error?

**Comment by seanhenry** [comment]
That would be the ideal solution but I don’t think there is a way to figure out if indexing is happening.

**Comment by LeonidKokhnovich** [comment]
Ok, closing the issue for now. If I see the problem again, I will dive into the code and try to come up with some solution. Thank you!
